namespace EwFrameworkAnalysis.Common.Models.Project;

/// <summary>
/// Root container for all project data - this is what gets saved to disk
/// </summary>
public class AnalysisProject
{
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public string? Title { get; set; }
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.Now;
    public DateTimeOffset LastModifiedAt { get; set; } = DateTimeOffset.Now;

    // User configures which data sources they have
    public List<DataSource> DataSources { get; set; } = [];

    // Assessment history (generated by application at runtime)
    public List<DataSourceAssessment> DataSourceAssessments { get; set; } = [];
}
