using System.Collections.Concurrent;
using System.ComponentModel.DataAnnotations;
using EwFrameworkAnalysis.Common.Assessors.EdFi;

namespace EwFrameworkAnalysis.UI;

/// ANALYSIS PROJECTS
/// <summary>
/// Root container for all project data - this is what gets saved to disk
/// </summary>
public class AnalysisProject
{
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public string? Title { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime LastModifiedAt { get; set; } = DateTime.UtcNow;

    // User configures which data sources they have
    public List<DataSource> DataSources { get; set; } = [];

    // Assessment history (generated by application at runtime)
    public List<DataSourceAssessment> DataSourceAssessments { get; set; } = [];
}


/// DATASOURCES

/// <summary>
/// A data source that can be assessed (API, SQL, Manual)
/// </summary>
public class DataSource
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string Name { get; set; } = string.Empty; // User-provided name like "District Ed-Fi API"
    public string? Description { get; set; }
    public bool Enabled { get; set; } = true;
    public DataSourceType Type { get; set; } // Which type of system this is
}

public enum DataSourceType
{
    [Display(Name = "Ed-Fi ODS API", Description = "Automated discovery & analysis")]
    EdFiApi,

    [Display(Name = "CEDS Data Warehouse", Description = "Upload SQL result sets from CEDS DW")]
    CedsDw,

    [Display(Name = "Manual Assessment", Description = "Flexible checklist for manual review")]
    Custom
}



// ASSESMENTS

/// <summary>
/// A complete assessment run across data sources at a point in time
/// </summary>
public class DataSourceAssessment
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string? Name { get; set; }
    public DateTime ConductedAt { get; set; } = DateTime.UtcNow;
    public string? Notes { get; set; }

    // All assessments from this session
    public List<DataElementAssessment> DataElementAssessments { get; set; } = [];
}

/// <summary>
/// Assessment result for a specific data element from a specific data source
/// </summary>
public class DataElementAssessment
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid AssessmentSessionId { get; set; }
    public string DataElementName { get; set; } = string.Empty;
    public Guid DataSourceId { get; set; }
    public DateTime AssessedAt { get; set; } = DateTime.UtcNow;

    // Assessment results
    public List<DataCharacteristicBase> Characteristics { get; set; } = [];
    public string? Remarks { get; set; }
    public bool? AvailabilityUserOverride { get; set; }
}



/// DATA CHARACTERISTICS
public abstract class DataCharacteristicBase
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string? Remarks { get; set; }
    public DateTime MeasuredAt { get; set; } = DateTime.UtcNow;
}

public class RecordCount : DataCharacteristicBase
{
    public RecordCount(int value)
    {
        Value = value;
    }

    public int Value { get; }
}

public class ReportedAvailability : DataCharacteristicBase
{
    public ReportedAvailability(AvailabilityJudgment value)
    {
        Value = value;
    }

    public AvailabilityJudgment Value { get; }
}

public enum AvailabilityJudgment
{
    Available,
    PartiallyAvailable,
    NotAvailable,
    InsufficientData
}

public class IntegerRange : DataCharacteristicBase
{
    public IntegerRange(int minimum, int maximum, string label)
    {
        if (maximum < minimum)
            throw new ArgumentException("Maximum must be greater than or equal to minimum");

        Minimum = minimum;
        Maximum = maximum;
        Label = label;
    }

    public int Minimum { get; }
    public int Maximum { get; }
    public string Label { get; }
}

public class Completeness : DataCharacteristicBase
{
    public Completeness(int totalRecords, int populatedRecords, string attributeName)
    {
        if (totalRecords < 0)
            throw new ArgumentException("Total records cannot be negative", nameof(totalRecords));
        if (populatedRecords < 0)
            throw new ArgumentException("Populated records cannot be negative", nameof(populatedRecords));
        if (populatedRecords > totalRecords)
            throw new ArgumentException("Populated records cannot exceed total records");

        TotalRecords = totalRecords;
        PopulatedRecords = populatedRecords;
        AttributeName = attributeName;
    }

    public int TotalRecords { get; }
    public int PopulatedRecords { get; }
    public string AttributeName { get; }
    public double Percentage => TotalRecords == 0 ? 0 : (PopulatedRecords * 100.0) / TotalRecords;
}

public class Distribution : DataCharacteristicBase
{
    public Distribution(Dictionary<string, int> counts, string label)
    {
        Counts = counts ?? throw new ArgumentNullException(nameof(counts));
        Label = label ?? throw new ArgumentNullException(nameof(label));
        TotalCount = counts.Values.Sum();
    }

    public Dictionary<string, int> Counts { get; }
    public string Label { get; }
    public int TotalCount { get; }

    public string FormatItem(string key, int count)
    {
        var percentage = TotalCount == 0 ? 0 : (count * 100.0 / TotalCount);
        return $"{key}: {count:N0} ({percentage:F1}%)";
    }
}





/// <summary>
/// Overall progress report for the assessment orchestration.
/// </summary>
public class AssessmentProgress
{
    /// <summary>
    /// Total number of assessors to run.
    /// </summary>
    public int TotalAssessors { get; set; }

    /// <summary>
    /// Number of assessors that have completed (successfully or with errors).
    /// </summary>
    public int CompletedAssessors { get; set; }

    /// <summary>
    /// Individual assessor progress reports.
    /// </summary>
    public List<AssessorProgress> AssessorProgresses { get; set; } = [];

    /// <summary>
    /// Calculates the percentage complete (0-100).
    /// </summary>
    public int PercentComplete => TotalAssessors == 0 ? 0 : (CompletedAssessors * 100) / TotalAssessors;
}

/// <summary>
/// Status of an individual assessor execution.
/// </summary>
public enum AssessorStatus
{
    Pending,
    Running,
    Completed,
    Failed
}

/// <summary>
/// Progress report for an individual assessor execution.
/// </summary>
public class AssessorProgress
{
    /// <summary>
    /// The name of the data element being assessed.
    /// </summary>
    public string DataElementName { get; set; } = string.Empty;

    /// <summary>
    /// The current status of the assessment.
    /// </summary>
    public AssessorStatus Status { get; set; }

    /// <summary>
    /// Optional error message if the assessment failed.
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// The completed assessment result, if successful.
    /// </summary>
    public DataElementAssessment? Result { get; set; }

    /// <summary>
    /// Current progress percentage (0-100) for this assessor, if available.
    /// </summary>
    public int? ProgressPercentage { get; set; }

    /// <summary>
    /// Current status message for this assessor (e.g., "Processing page 3 of 10").
    /// </summary>
    public string? StatusMessage { get; set; }

    /// <summary>
    /// Log messages from the assessor execution.
    /// </summary>
    public List<string> LogMessages { get; set; } = [];
}

/// <summary>
/// Context object passed to assessors for reporting progress and logging.
/// </summary>
public class AssessorContext
{
    private readonly Action<int?, string?>? _progressCallback;
    private readonly Action<string>? _logCallback;

    public AssessorContext(Action<int?, string?>? progressCallback = null, Action<string>? logCallback = null)
    {
        _progressCallback = progressCallback;
        _logCallback = logCallback;
    }

    /// <summary>
    /// Reports progress percentage and optional status message.
    /// </summary>
    /// <param name="percentage">Progress percentage (0-100), or null to clear.</param>
    /// <param name="statusMessage">Optional status message to display.</param>
    public void ReportProgress(int? percentage, string? statusMessage = null)
    {
        _progressCallback?.Invoke(percentage, statusMessage);
    }

    /// <summary>
    /// Logs a message for debugging or display purposes.
    /// </summary>
    /// <param name="message">The message to log.</param>
    public void Log(string message)
    {
        _logCallback?.Invoke(message);
    }
}


//public interface IEdFiAssessor
//{
//    string DataElementName { get; }
//    Task<DataElementAssessment> AssessAsync(HttpClient httpClient, DataSource dataSource, AssessorContext context);
//    string AssessmentDescription { get; }
//}

/// <summary>
/// Orchestrates the execution of multiple Ed-Fi assessors against a data source.
/// </summary>
public class EdFiAssessmentOrchestrator
{
    private readonly IEnumerable<IEdFiAssessor> _assessors;
    private readonly int _maxDegreeOfParallelism;

    /// <summary>
    /// Initializes a new instance of the orchestrator.
    /// </summary>
    /// <param name="assessors">Collection of all available Ed-Fi assessors to run.</param>
    /// <param name="maxDegreeOfParallelism">
    /// Maximum number of assessors to run concurrently. 
    /// Default is 4, which balances throughput with API rate limiting concerns.
    /// Use 1 for sequential execution.
    /// </param>
    public EdFiAssessmentOrchestrator(
        IEnumerable<IEdFiAssessor> assessors,
        int maxDegreeOfParallelism = 4)
    {
        _assessors = assessors ?? throw new ArgumentNullException(nameof(assessors));

        if (maxDegreeOfParallelism < 1)
            throw new ArgumentOutOfRangeException(nameof(maxDegreeOfParallelism), "Must be at least 1");

        _maxDegreeOfParallelism = maxDegreeOfParallelism;
    }

    /// <summary>
    /// Executes all assessors against the specified data source and collects results.
    /// </summary>
    /// <param name="httpClient">
    /// An HTTP client configured with the Ed-Fi API base address and authentication.
    /// </param>
    /// <param name="dataSource">The data source configuration being assessed.</param>
    /// <param name="assessmentName">Optional name for this assessment session.</param>
    /// <param name="notes">Optional notes about this assessment session.</param>
    /// <param name="progress">
    /// Optional progress reporter for tracking assessment execution in real-time.
    /// </param>
    /// <param name="continueOnError">
    /// If true, continues executing remaining assessors even if some fail.
    /// If false, stops execution on the first error. Default is true.
    /// </param>
    /// <param name="ct">Cancellation token to cancel the assessment operation.</param>
    /// <returns>
    /// A completed DataSourceAssessment containing all successful assessment results.
    /// Failed assessments are omitted from the results but reported via progress.
    /// </returns>
    /// <exception cref="ArgumentNullException">
    /// Thrown when httpClient or dataSource is null.
    /// </exception>
    /// <exception cref="TaskCanceledException">
    /// Thrown when the operation is cancelled via the cancellation token.
    /// </exception>
    /// <remarks>
    /// This method executes assessors in parallel (up to maxDegreeOfParallelism).
    /// Progress reports are thread-safe and can be monitored in real-time.
    /// For Blazor WebAssembly scenarios, consider using maxDegreeOfParallelism=1
    /// to avoid browser threading limitations.
    /// </remarks>
    public async Task<DataSourceAssessment> RunAssessmentsAsync(
        HttpClient httpClient,
        DataSource dataSource,
        string? assessmentName = null,
        string? notes = null,
        IProgress<AssessmentProgress>? progress = null,
        bool continueOnError = true,
        CancellationToken ct = default)
    {
        if (httpClient == null)
            throw new ArgumentNullException(nameof(httpClient));
        if (dataSource == null)
            throw new ArgumentNullException(nameof(dataSource));

        var assessment = new DataSourceAssessment
        {
            Name = assessmentName ?? $"Ed-Fi Assessment - {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}",
            Notes = notes,
            ConductedAt = DateTime.UtcNow
        };

        var assessorList = _assessors.ToList();
        var progressState = new AssessmentProgress
        {
            TotalAssessors = assessorList.Count,
            CompletedAssessors = 0,
            AssessorProgresses = [.. assessorList.Select(a => new AssessorProgress
            {
                DataElementName = a.DataElementName,
                Status = AssessorStatus.Pending
            })]
        };

        // Report initial state
        progress?.Report(progressState);

        // Thread-safe collection for results
        var results = new ConcurrentBag<DataElementAssessment>();
        var progressLock = new object();

        // Execute assessors with controlled parallelism
        var parallelOptions = new ParallelOptions
        {
            MaxDegreeOfParallelism = _maxDegreeOfParallelism,
            CancellationToken = ct
        };

        try
        {
            await Parallel.ForEachAsync(
                assessorList.Select((assessor, index) => (assessor, index)),
                parallelOptions,
                async (item, token) =>
                {
                    var (assessor, index) = item;

                    // Update status to running
                    UpdateProgress(index, AssessorStatus.Running);

                    // Create context for this assessor
                    var context = new AssessorContext(
                        progressCallback: (percentage, statusMessage) =>
                        {
                            UpdateProgressDetails(index, percentage, statusMessage);
                        },
                        logCallback: (message) =>
                        {
                            AddLogMessage(index, message);
                        }
                    );

                    try
                    {
                        var result = await assessor.AssessAsync(httpClient, dataSource, context);
                        result.AssessmentSessionId = assessment.Id;
                        results.Add(result);

                        // Update status to completed
                        UpdateProgress(index, AssessorStatus.Completed, result: result);
                    }
                    catch (Exception ex)
                    {
                        // Update status to failed
                        UpdateProgress(index, AssessorStatus.Failed, errorMessage: ex.Message);

                        if (!continueOnError)
                            throw;
                    }
                });
        }
        catch (TaskCanceledException)
        {
            // Add cancellation info to notes
            assessment.Notes = string.IsNullOrWhiteSpace(assessment.Notes)
                ? "Assessment was cancelled"
                : $"{assessment.Notes}\n\nAssessment was cancelled";
            throw;
        }

        // Collect all successful results
        assessment.DataElementAssessments = [.. results.OrderBy(r => r.DataElementName)];

        return assessment;

        void UpdateProgress(int index, AssessorStatus status, string? errorMessage = null, DataElementAssessment? result = null)
        {
            if (progress == null) return;

            lock (progressLock)
            {
                progressState.AssessorProgresses[index].Status = status;
                progressState.AssessorProgresses[index].ErrorMessage = errorMessage;
                progressState.AssessorProgresses[index].Result = result;

                if (status is AssessorStatus.Completed or AssessorStatus.Failed)
                {
                    progressState.CompletedAssessors++;
                }

                ReportProgress();
            }
        }

        void UpdateProgressDetails(int index, int? percentage, string? statusMessage)
        {
            if (progress == null) return;

            lock (progressLock)
            {
                progressState.AssessorProgresses[index].ProgressPercentage = percentage;
                progressState.AssessorProgresses[index].StatusMessage = statusMessage;
                ReportProgress();
            }
        }

        void AddLogMessage(int index, string message)
        {
            if (progress == null) return;

            lock (progressLock)
            {
                progressState.AssessorProgresses[index].LogMessages.Add($"[{DateTime.Now:HH:mm:ss}] {message}");
                ReportProgress();
            }
        }

        void ReportProgress()
        {
            // Create a deep copy for thread safety
            var reportCopy = new AssessmentProgress
            {
                TotalAssessors = progressState.TotalAssessors,
                CompletedAssessors = progressState.CompletedAssessors,
                AssessorProgresses = [.. progressState.AssessorProgresses.Select(ap => new AssessorProgress
                {
                    DataElementName = ap.DataElementName,
                    Status = ap.Status,
                    ErrorMessage = ap.ErrorMessage,
                    Result = ap.Result,
                    ProgressPercentage = ap.ProgressPercentage,
                    StatusMessage = ap.StatusMessage,
                    LogMessages = [.. ap.LogMessages]
                })]
            };

            progress.Report(reportCopy);
        }
    }
}
