using System.ComponentModel.DataAnnotations;

namespace EwFrameworkAnalysis.UI;

/// ANALYSIS PROJECTS
/// <summary>
/// Root container for all project data - this is what gets saved to disk
/// </summary>
public class AnalysisProject
{
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public string? Title { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime LastModifiedAt { get; set; } = DateTime.UtcNow;

    // User configures which data sources they have
    public List<DataSource> DataSources { get; set; } = [];

    // Assessment history (generated by application at runtime)
    public List<DataSourceAssessment> DataSourceAssessments { get; set; } = [];
}


/// DATASOURCES

/// <summary>
/// A data source that can be assessed (API, SQL, Manual)
/// </summary>
public class DataSource
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string Name { get; set; } = string.Empty; // User-provided name like "District Ed-Fi API"
    public string? Description { get; set; }
    public bool Enabled { get; set; } = true;
    public DataSourceType Type { get; set; } // Which type of system this is
}

public enum DataSourceType
{
    [Display(Name = "Ed-Fi ODS API", Description = "Automated discovery & analysis")]
    EdFiApi,

    [Display(Name = "CEDS Data Warehouse", Description = "Upload SQL result sets from CEDS DW")]
    CedsDw,

    [Display(Name = "Manual Assessment", Description = "Flexible checklist for manual review")]
    Custom
}



// ASSESMENTS

/// <summary>
/// A complete assessment run across data sources at a point in time
/// </summary>
public class DataSourceAssessment
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string? Name { get; set; }
    public DateTime ConductedAt { get; set; } = DateTime.UtcNow;
    public string? Notes { get; set; }

    // All assessments from this session
    public List<DataElementAssessment> DataElementAssessments { get; set; } = [];
}

/// <summary>
/// Assessment result for a specific data element from a specific data source
/// </summary>
public class DataElementAssessment
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid AssessmentSessionId { get; set; }
    public string DataElementName { get; set; } = string.Empty;
    public Guid DataSourceId { get; set; }
    public DateTime AssessedAt { get; set; } = DateTime.UtcNow;

    // Assessment results
    public List<DataCharacteristicBase> Characteristics { get; set; } = [];
    public string? Remarks { get; set; }
    public bool? AvailabilityUserOverride { get; set; }
}



/// DATA CHARACTERISTICS
public abstract class DataCharacteristicBase
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string? Remarks { get; set; }
    public DateTime MeasuredAt { get; set; } = DateTime.UtcNow;
}

public class RecordCount : DataCharacteristicBase
{
    public RecordCount(int value)
    {
        Value = value;
    }

    public int Value { get; }
}

public class ReportedAvailability : DataCharacteristicBase
{
    public ReportedAvailability(AvailabilityJudgment value)
    {
        Value = value;
    }

    public AvailabilityJudgment Value { get; }
}

public enum AvailabilityJudgment
{
    Available,
    PartiallyAvailable,
    NotAvailable,
    InsufficientData
}

public class IntegerRange : DataCharacteristicBase
{
    public IntegerRange(int minimum, int maximum, string label)
    {
        if (maximum < minimum)
            throw new ArgumentException("Maximum must be greater than or equal to minimum");

        Minimum = minimum;
        Maximum = maximum;
        Label = label;
    }

    public int Minimum { get; }
    public int Maximum { get; }
    public string Label { get; }
}

public class Completeness : DataCharacteristicBase
{
    public Completeness(int totalRecords, int populatedRecords, string attributeName)
    {
        if (totalRecords < 0)
            throw new ArgumentException("Total records cannot be negative", nameof(totalRecords));
        if (populatedRecords < 0)
            throw new ArgumentException("Populated records cannot be negative", nameof(populatedRecords));
        if (populatedRecords > totalRecords)
            throw new ArgumentException("Populated records cannot exceed total records");

        TotalRecords = totalRecords;
        PopulatedRecords = populatedRecords;
        AttributeName = attributeName;
    }

    public int TotalRecords { get; }
    public int PopulatedRecords { get; }
    public string AttributeName { get; }
    public double Percentage => TotalRecords == 0 ? 0 : (PopulatedRecords * 100.0) / TotalRecords;
}

public class Distribution : DataCharacteristicBase
{
    public Distribution(Dictionary<string, int> counts, string label)
    {
        Counts = counts ?? throw new ArgumentNullException(nameof(counts));
        Label = label ?? throw new ArgumentNullException(nameof(label));
        TotalCount = counts.Values.Sum();
    }

    public Dictionary<string, int> Counts { get; }
    public string Label { get; }
    public int TotalCount { get; }

    public string FormatItem(string key, int count)
    {
        var percentage = TotalCount == 0 ? 0 : (count * 100.0 / TotalCount);
        return $"{key}: {count:N0} ({percentage:F1}%)";
    }
}
